In [32]:
# import numpy
# create array x
import numpy as np
x=np.ones([5])
print x.T
x=x.reshape(5,1)
print x

[ 1.  1.  1.  1.  1.]
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]


In [14]:
# print the shape of x
print x.shape

(5, 5)


In [21]:
# create a two dimensional array
x=np.ones([4,3])
print x

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [22]:
# print shape of 2d array
x.shape

(4, 3)

In [23]:
# reshape the array to 2 x 6
x.reshape(2,6)

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [24]:
# reshape the array to 1 x 12
x.reshape(1,12)

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [27]:
# transpose the array
x=x.T
print x

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [34]:
# indexing method 1
a=np.ones((1,5))
b=np.ones((5,1))
print np.dot(a,b)

[[ 5.]]


In [9]:
# indexing method 2

In [13]:
# indexing method 3

In [12]:
# indexing method 4

In [11]:
# indexing method 5

In [10]:
# indexing method 6