### List comprehension independent practice

Each problem should be completed with a single list (or dictionary) comprehension!

In [1]:
import pandas as pd
import numpy as np
import string

#### Easy problems

##### 1. convert each string from lowercase to uppercase

[Hint: python strings can be turned to uppercase by appending: .upper(), e.g 'hello'.upper()]

In [3]:
strings = ['black','Yellow','ReD','GreeN','BLUe']
strings2=[ x.upper() for x in strings]
print strings2

['BLACK', 'YELLOW', 'RED', 'GREEN', 'BLUE']


##### 2. take the numbers in the list and keep only the even numbers

[Hint: the modulo operator **%** can be used to calculate the remainder, e.g. 5 % 2 == 1]

In [5]:
numbers = [1,2,3,4,5,6,7,8,9,10]
num_even=[x for x in numbers if x%2==0]
print num_even

[2, 4, 6, 8, 10]


##### 3. convert to 'v' if a character is a vowel and 'c' if a consonant, otherwise convert to '?'

In [17]:
characters = ['a','f',None,'k','l','1',12,'e','e',-1,'i','b','p']
alphabet = list(string.ascii_lowercase)
vowels = ['a','e','i','o','u']
char_check=['v' if x in vowels else 'c' if x in alphabet else '?' for x in characters]
print char_check

['v', 'c', '?', 'c', 'c', '?', '?', 'v', 'v', '?', 'v', 'c', 'c']


#### Medium problems

##### 4. calculate the means of the numbers in each list that lie between 0 and 100 (inclusive)

In [1]:
number_sets = [[1,50,-40,20,90], [1004,1002,101,-90,40,34], [-1,-2,34,55,77,109]]
lis=[]
for x in number_sets:
    lis.insert(0,[])
    for y in x:
        if y<101 and y>-1:
            lis[0].append(y)
print lis
lis2=[]
for x in lis:
    lis2.insert(0,[])
    sum=0
    len=0
    for y in x:
        sum+=y
        len+=1
    r=[float(sum),float(len)]
    lis2[0].append(r)
print lis2
lis3=[]
for x in lis2:
    mean=x[0][0]/x[0][1]
    lis3.append(mean)
print lis3

[[34, 55, 77], [40, 34], [1, 50, 20, 90]]
[[[161.0, 4.0]], [[74.0, 2.0]], [[166.0, 3.0]]]
[40.25, 37.0, 55.333333333333336]


##### 5. for each string in each list, if the index of the strings is even, join them like: 'item1 item2'. Otherwise join them like: 'item2 item1'.

In [12]:
strings1 = ['alpha','bravo','charlie','delta']
strings2 = ['echo','foxtrot','golf','hotel']
i=2
strings=[]
for x,y in zip(strings1,strings2):
    if i%2==0:
        strings.append(x+' '+y)
        i+=1
    else:
        strings.append(y+' '+x)
        i+=1
print strings

['alpha echo', 'foxtrot bravo', 'charlie golf', 'hotel delta']


##### 6. create a pandas dataframe from the columns and associated values where each column is the first five multiples of the values:

In [52]:
import numpy as np
import pandas as pd
indices = ['five','seven','twelve']
values = [5, 7, 12]
multiples = [1, 2, 3, 4, 5]
x=np.array([[5],[7],[12]])
y=np.array(multiples)
one=np.ones((3,5))
z=np.multiply(x,one)
z=np.multiply(y,z)
print z
pd.DataFrame(z,index=indices,columns=multiples)

[[  5.  10.  15.  20.  25.]
 [  7.  14.  21.  28.  35.]
 [ 12.  24.  36.  48.  60.]]


1     2     3     4     5
five     5.0  10.0  15.0  20.0  25.0
seven    7.0  14.0  21.0  28.0  35.0
twelve  12.0  24.0  36.0  48.0  60.0

#### Hard problems

##### 7. manually calculate the median of the first n numbers (from list "N") in list "X"

In [ ]:
N = [12, 5, 6, 8, 10]
X = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


##### 8. combine into a flat list: 

1. iterate the elements of one list 
2. iteratively multiply by them by the elements in the second list
3. then iteratively subtract the elements in a third list

e.g:

    a = [1,2]
    b = [0,1]
    c = [1,2]
    output = [0,0,0,-1,0,0,1,0]

In [ ]:
a = [9,7,5]
b = [10,5,1]
c = [1,2,3]
